services:
  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: content_sync_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - content-sync-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # WordPress (Bedrock)
  wordpress:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: content_sync_wp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
      - wp_uploads:/var/www/html/web/app/uploads
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    networks:
      - content-sync-network

  # Next.js Frontend
  nextjs:
    container_name: content_sync_next
    build: 
      context: ./frontend 
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    networks:
      - content-sync-network
    ports:
      - "3000:3000"
    depends_on:
      wordpress:
        condition: service_started


  # Nginx
  nginx:
    image: nginx:alpine
    container_name: content_sync_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      wordpress:
        condition: service_started
    networks:
      - content-sync-network

networks:
  content-sync-network:
    driver: bridge

volumes:
  db_data:
  wp_uploads: