server {
    listen 80;
    root /var/www/html/web;
    index index.php;

    # Обработка PHP через FastCGI
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;
    }

    # запросы к WordPress
    location ~ ^/(wp-admin|wp-json|wp-login\.php|wp-includes|wp-content|wp) {
        try_files $uri $uri/ /index.php?$args;
    }

    # Все остальное — на Next.js
    location / {
        proxy_pass http://nextjs:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}